CLOUDP-155724: No way to stop mongonet TCP or GRPC Server
mongodb/mongonet pull request #124
Opened 2023-01-27 21:38 UTC by pstefek-mongo

Jira: https://jira.mongodb.org/browse/CLOUDP-155724

2023-01-27 21:43 UTC, pstefek-mongo commented on proxy.go
> +					p.gRPCServer.GracefulStop()
You might wonder, what happens if `p.gRPCServer.GracefulStop()` is called before `p.gRPCServer.Run()` The gprc server package is aware of this case and will just error for fail. https://github.com/grpc/grpc-go/blob/c1d7d7acc3d14788d07ded8be9cd74c136084294/server.go#L775

2023-01-27 21:44 UTC, pstefek-mongo commented on proxy.go
> +					p.gRPCServer.grpcServer.Stop()
You might wonder, what happens if `p.gRPCServer.grpcServer.Stop()` is called before `p.gRPCServer.Run()` The gprc server package is aware of this case and will just error for fail. https://github.com/grpc/grpc-go/blob/c1d7d7acc3d14788d07ded8be9cd74c136084294/server.go#L775

2023-01-27 21:45 UTC, pstefek-mongo commented on server.go
> +	ctx, cancelCtx := context.WithCancel(ctx)
For the tcpServer just allow us to pass our own cancelable parent context in

2023-01-27 21:52 UTC, pstefek-mongo commented
@denniskuczynski for the grpc
@tolsen for general multi threading and the tcp server

2023-01-27 21:54 UTC, pstefek-mongo commented on proxy.go
>  			grpcErr = p.gRPCServer.Run()
There seems to be no easy way I found to pipe a context into the grpc server so I decided to create a separate goroutine which just to see if the context is cancelled and if so kills the server

2023-01-27 21:55 UTC, pstefek-mongo commented on proxy.go
> +					p.gRPCServer.grpcServer.Stop()
This is also fine to call if the server has already been shutdown

2023-01-30 18:21 UTC, tolsen requested changes
Please change the PR description to describe the change, and not the problem.

Otherwise the code looks fine.  Well, I see some old code that may be a context leak, but it's not new code. lol

2023-01-30 19:35 UTC, denniskuczynski commented on proxy.go
>  			grpcErr = p.gRPCServer.Run()
I think it would probably be cleaner from an API perspective to put the context waiting in the GrpcServer's Run method and pass the context into the constructor to be symmetric with the TCPServer impl.

2023-01-31 19:37 UTC, pstefek-mongo commented on proxy.go
>  			grpcErr = p.gRPCServer.Run()
done!

2023-02-02 18:59 UTC, denniskuczynski commented on server.go
> +	defer s.cancelCtx()
I may not be familiar with the `context` API, but I don't think we want to explicitly cancel this context within here -- I think we want the users who pass a context value to `NewGRPCServer()` to be able to cancel that context.  So I don't think we need `cancelCtx` within here.  We just want to ensure that we listen to the `Done()` channel to shutdown the server. Does that make sense?

2023-02-02 19:38 UTC, tolsen commented on server.go
> +	defer s.cancelCtx()
This is a subcontext that he is cancelling.  It is created on line 342.

We have to cancel it at some point, since we are creating it inside NewGRPCServer().  Otherwise we will have a context leak.

Cancelling subcontexts do not affect the parent context.  The reverse is not true though.

2023-02-03 15:17 UTC, pstefek-mongo commented on server.go
> +	defer s.cancelCtx()
I'm with Tim here

2023-02-03 15:21 UTC, denniskuczynski commented on server.go
> +	defer s.cancelCtx()
right, but do we need to create the sub context at all?

2023-02-03 15:23 UTC, denniskuczynski commented on server.go
> +	defer s.cancelCtx()
oh, I see what you're saying.  You're using this subcontext to cleanup the new goroutine listening for the parent cancellation.  👍

2023-02-03 15:23 UTC, denniskuczynski commented on server.go
> +	defer s.cancelCtx()
and that wouldn't happen if they didn't pass in a cancellable parent context

2023-02-03 15:25 UTC, pstefek-mongo commented on server.go
> +	defer s.cancelCtx()
or they just didn't cancel it and the server stopped for some other reason (error, etc)

2023-02-03 15:26 UTC, denniskuczynski approved these changes
LGTM 👍

2023-02-03 19:26 UTC, tolsen approved these changes

2023-02-03 20:25 UTC, merged