Go driver connection pool
mongodb/mongonet pull request #55
Opened 2020-10-01 19:16 UTC by TomerYakir

2020-10-01 19:23 UTC, divjotarora commented
test

2020-10-01 19:24 UTC, divjotarora reviewed
test

2020-10-07 15:05 UTC, tolsen requested changes

2020-10-07 15:05 UTC, tolsen commented on proxy.go
> +	// TODO - should probably return nil for mongoConn so we don't attempt to close twice
is this TODO important to do before merging?

2020-10-07 15:05 UTC, tolsen commented on server_test.go
> +		if cmdName == "find" {
changing all these ifs to a switch statement that switches on cmdName may compile to faster code

2020-10-07 15:05 UTC, tolsen commented on server_test.go
> +			ns := fmt.Sprintf("%s.%s", db, cmd[0].Value.(string)) // TODO: check type cast?
should we address the TODO?

2020-10-07 15:10 UTC, iwysiu approved these changes
lgtm with comments

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +				if mongoConn != nil {
Question: why are we calling `mongoConn.Close()` in just this error case? Other error cases do `return mongoConn, err` and I think the `DoLoopTemp` function calls `mongoConn.Close()` if the error is non-nil. Can we do the same here?

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +				return mongoConn, NewStackErrorf("couldn't send error response to client %v", err)
Could we preserve the original error and include it in this message like this:
```
if respondErr := ps.RespondWithError(m, err); respondErr != nil {
    return mongoConn, NewStackErrorf("couldn't send error response to client; original error: %v, error sending response: %v, err, respondErr)
}
```

This way, it'll be included in the `WARN` verbosity log in `DoLoopTemp` instead of only being logged at `INFO` verbosity in `RespondWithError`.

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +func (ps *ProxySession) getMongoConnection() (driver.Connection, error) {
Seems like this is only called in one location and the caller immediately wraps it in `MongoConnectionWrapper`. Can we change this to directly return `(*MongoConnectionWrapper, error)` instead?

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +	topo := extractTopology(ps.proxy.MongoClient)
This could be a potentially expensive reflection-based operation. Would it be possible to store this directly on `ps.proxy` so it's only done once?

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> -			return nil, nil
What was the motivation for changing these from `nil` to `mongoConn`?

2020-10-07 17:37 UTC, divjotarora commented on server_test.go
> +	err = client.Disconnect(ctx)
nit: This and the error handling below is equivalent to `return client.Disconnect(ctx)`.

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +		resp, err := ReadMessageFromBytes(ret)
Can you leverage the existing `ReadMessage` function by using [`bytes.NewReader`](https://golang.org/pkg/bytes/#NewReader)?

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +type MongoConnectionWrapper struct {
It could be useful to have an additional `expirable` field of type [`driver.Expirable](https://github.com/mongodb/mongo-go-driver/blob/90a0db4834452f0d85433bfef1a1799318384cec/x/mongo/driver/driver.go#L64). You should be able to directly cast `conn` to a `driver.Expirable` without any issues.

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +		if m.conn != nil && m.conn.ID() != "<closed>" {
Instead of checking for the special `<closed>` ID, you can cast to `driver.Expirable` and use the `Alive` function.

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +			ec, ok := m.conn.(*topology.Connection)
Use `driver.Expirable` instead of `*topology.Connection`.

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +	if m.conn.ID() != "<closed>" {
Same comment here about casting to `driver.Expirable` and using the `Alive` method.

2020-10-07 17:37 UTC, divjotarora commented on proxy.go
> +		mongoConn.bad = true
You might not need to mark the connection as "bad" here. The driver will close the socket when it gets a socket error during `WriteWireMessage`, so there's no need to do an additional explicit `Expire` call in `MongoConnectionWrapper.Close()`. Connections can be closed multiple times, though, so it's not incorrect to have this. The `Expire` call will acquire a mutex, but it should be uncontended and therefore shouldn't block, so this might be a micro-optimization to think about later on.

2020-10-07 17:59 UTC, TomerYakir commented on proxy.go
> +	// TODO - should probably return nil for mongoConn so we don't attempt to close twice
yeah - handling this now

2020-10-07 18:10 UTC, TomerYakir commented on mongo_error.go
> +	doc := bson.D{{"ok", 0}}
I'm not 100% sure if the order matters, but as far as I've seen, mongo always returned the fields in that order so keeping this as is.
btw, this method wasn't actually changed as part of this PR, just moved around.

2020-10-07 18:42 UTC, TomerYakir commented on proxy.go
> +				if mongoConn != nil {
yeah, I'm not sure why were doing that either. I'll see if changing this doesn't break anything ¯\_(ツ)_/¯

2020-10-07 18:52 UTC, TomerYakir commented on proxy.go
> +	topo := extractTopology(ps.proxy.MongoClient)
good catch! changed.

2020-10-07 18:52 UTC, TomerYakir commented on proxy.go
> -			return nil, nil
that was a mistake - changed!

2020-10-07 19:03 UTC, TomerYakir commented on proxy.go
> +		resp, err := ReadMessageFromBytes(ret)
I was following Louisa's comment here - https://github.com/mongodb/mongonet/compare/drivertest#diff-ddf6a9e7c9b2d4f21e3a3eabfe7c7d77R289 - but might have misinterpreted her intention?

2020-10-07 19:14 UTC, divjotarora commented on proxy.go
> +		resp, err := ReadMessageFromBytes(ret)
In that case, I'm fine with having them be separate. It might be possible to combine some the code duplicated between `ReadMessage` and `ReadMessageFromBytes` to clean things up. For example, the size validation can probably be delegated to a helper function and all of the code that happens after `ReadMessage` reads the remaining bytes into `restBuf` can be shared between the two.

2020-10-07 19:34 UTC, TomerYakir commented on proxy.go
> +		mongoConn.bad = true
cool - btw - is the same true for `ReadWireMessage`?

2020-10-07 19:35 UTC, divjotarora commented on proxy.go
> +		mongoConn.bad = true
Yeah, it should be the same. Also, forgot to ask in my original comment, but do we have tests for these cases? If not, it might be worth trying to add those if we're considering this optimization.

2020-10-07 19:58 UTC, TomerYakir commented on proxy.go
> +type MongoConnectionWrapper struct {
`conn` is of type `driver.Connection`. Did you mean I should be able to do `driver.Expirable(conn)`?
I'm getting an error:
```
cannot convert conn (type driver.Connection) to type driver.Expirable:
	driver.Connection does not implement driver.Expirable (missing Alive method)
```

2020-10-07 20:04 UTC, TomerYakir commented on proxy.go
> +		mongoConn.bad = true
We don't have explicit tests for that, but our application int tests have a "hostile" conditions section that's bound to hit those, but I'll look into adding some tests to mongonet to simulate errors on ReadWireMessage and WriteWireMessage.

2020-10-07 20:06 UTC, divjotarora commented on proxy.go
> +type MongoConnectionWrapper struct {
Can you do `conn.(driver.Expirable)`?

2020-10-07 20:16 UTC, TomerYakir commented on proxy.go
> +type MongoConnectionWrapper struct {
derp. yes

2020-10-08 14:49 UTC, tolsen requested changes

2020-10-08 14:49 UTC, tolsen commented on proxy.go
> +		logger.Logf(slogger.ERROR, "Recovering from mongonet panic. error is: %v \n stack traces: %v", r, stacktraces.String())
Please logger.Flush() before panicking

2020-10-08 14:49 UTC, tolsen commented on server_test.go
> +			ns := fmt.Sprintf("%s.%s", db, cmd[0].Value.(string)) // TODO: check type cast?
TODO is still here

2020-10-08 16:25 UTC, TomerYakir commented on proxy.go
> +		logger.Logf(slogger.ERROR, "Recovering from mongonet panic. error is: %v \n stack traces: %v", r, stacktraces.String())
fixed

2020-10-08 16:32 UTC, tolsen approved these changes

2020-10-08 19:52 UTC, iwysiu approved these changes

2020-10-08 20:12 UTC, divjotarora reviewed
Looks good! Just some remaining questions about edge cases and when we expect them to happen.

2020-10-08 20:12 UTC, divjotarora commented on proxy.go
> +	if mongoConn == nil || !mongoConn.expirableConn.Alive() {
Do we expect there to be cases where `DoLoopTemp` passed in a `mongoConn` value that isn't alive or is this here as a defensive check?

2020-10-08 20:44 UTC, divjotarora commented
@TomerYakir Forgot to mention this in my last review, but if we're changing the behavior to not mark the proxy to MongoDB connection as "bad" if the `ReadWireMessage` or `WriteWireMessage` calls fail, I think we should figure out ways to unit test that inside mongonet. If you agree, feel free to reach out in the Slack channel and we can brainstorm ways to make those functions fail.

2020-10-08 23:55 UTC, kevinAlbs commented on proxy.go
> +	d := e.FieldByName("deployment")
IIUC this is reaching inside `mongo.Client` to grab the private `deployment` field. I assume this is all ok for now, until GODRIVER-1760 is implemented. Should this be checking for the zero value? If `deployment` were renamed, I'm not sure what type of error would occur.

2020-10-08 23:55 UTC, kevinAlbs commented on sock.go
> +	case OP_REPLY:
I assume this is for completeness in mongonet, but the only op codes Atlas Proxy needs to support are `OP_QUERY`, `OP_REPLY`, and `OP_MSG`, right?

2020-10-08 23:55 UTC, kevinAlbs commented on sock.go
> +	if headerSize > int32(200*1024*1024) {
It looks like this was moved, but I'm curious if there is a reason behind 200MB. I'd think `maxMessageSizeBytes` would be the number to check.

2020-10-09 00:28 UTC, divjotarora commented on sock.go
> +	case OP_REPLY:
I don't think that's true. IIUC, there will essentially be two modes for the proxy: one for shared and one for serverless. Seems like we're making the assumption that the serverless proxy will only have to support 5.0+, so it only needs to support those three opcodes (though the exact decision about that is pending Louisa's opinion on the CLOUDP ticket about bumping minWireVersion). I'm guessing the shared tier proxy still needs to continue supporting all of these opcodes for backwards compatibility, though none of our drivers would send them.

2020-10-09 00:28 UTC, divjotarora commented on proxy.go
> +	d := e.FieldByName("deployment")
If the `deployment` field doesn't exist, `FieldByName` will return a zero-valued `reflect.Value`  and the `d.Type()` call on the next line will panic. I'm fine with this behavior, but I agree that adding an explicit `d.IsZero` check would make things more explicit.

2020-10-09 09:57 UTC, TomerYakir commented on proxy.go
> +		if m.conn != nil && m.expirableConn.Alive() {
This is definitely redundant at this point (see the condition on line 55) so I removed it.
As for the condition on line 55 - yes, it's just defensive programming and I bumped the log level so we can further look into if that ever happens.

2020-10-09 09:58 UTC, TomerYakir commented on proxy.go
> +	if mongoConn == nil || !mongoConn.expirableConn.Alive() {
this is just a defensive check.

2020-10-09 09:59 UTC, TomerYakir commented on cmd/straight_proxy/straight_proxy.go
>  	proxy.OnSSLConfig(nil)
added a check

2020-10-09 13:16 UTC, TomerYakir commented on sock.go
> +	if headerSize > int32(200*1024*1024) {
yeah, that was moved and I'm unsure about that figure. I'll file a separate ticket to look into that value.

2020-10-13 10:16 UTC, TomerYakir commented
@divjotarora tests added - RFAL

2020-10-13 14:29 UTC, divjotarora reviewed
All nits/minor comments in the new tests. Correctness-wise everything LGTM.

2020-10-13 14:29 UTC, divjotarora commented on proxy_test.go
> +func GetConnCreated(p *Proxy) int64 {
nit: If the caller has access to a `Proxy` instance, can they directly call `p.GetConnectionsCreated()` rather than going through this function?

2020-10-13 14:29 UTC, divjotarora commented on proxy_test.go
> +	opts := options.Client().ApplyURI(fmt.Sprintf("mongodb://localhost:%d", proxyPort))
Seems like the code to create a `Client` could be shared by this function and `enableFailPoint`/`disableFailPoint`.

2020-10-13 14:29 UTC, divjotarora commented on proxy_test.go
> +		// {"mode", bson.D{{"times", 5}}},
nit: remove this commented-out line

2020-10-13 14:29 UTC, divjotarora commented on proxy_test.go
> +	res := client.Database("admin").RunCommand(ctx, cmd)
This should probably be
```
return client.Database("admin").RunCommand(ctx, cmd).Err()
```

I'm assuming the `Println` below is leftover debugging. If it's there intentionally, you can instead do
```
res, err := client.Database("admin").RunCommand(ctx, cmd).DecodeBytes()
fmt.Println(res)
return err
```

2020-10-13 14:29 UTC, divjotarora commented on proxy_test.go
> +	res := client.Database("admin").RunCommand(ctx, cmd)
Same comment here about using either `Err` or `DecodeBytes`.

2020-10-13 14:29 UTC, divjotarora commented on proxy_test.go
> +			wg.Done()
nit: The wait group `Done` call is generally done using `defer wg.Done()` as the first call of the goroutine. This ensures that the wait group is decremented even if another call in the goroutine panics.

2020-10-13 19:51 UTC, divjotarora approved these changes
LGTM!

2020-10-13 20:01 UTC, merged