Create request and response timing and errors metric hooks
mongodb/mongonet pull request #62
Opened 2020-11-17 20:14 UTC by varunravi98

This PR adds hooks to measure request and response time and track the number of errors encountered during this process. The hook is designed to be analogous to `ProxyInterceptor` and `ProxyInterceptorFactory`, with `MetricsHook` and `MetricsHookFactory`, respectively. Each `ProxyConfig` now contains a `MetricsHookFactory` field called `CollectorHookFactory`. A non-nil type that implements `CollectorHookFactory` implements the `NewHook()` method, which enables it to create new `MetricsHook`s. Meanwhile, the `ProxySession` type now includes two additional fields: `hooks`, which is a map of `MetricsHook`s, and `isMetricsEnabled`, a bool. When `CreateWorker` is called to generate a new `ProxySession`, `hooks` is populated with `MetricsHook`s generated from the `ProxyConfig`'s `CollectorHookFactory` field (provided that it is non-nil). At the moment, the `MetricsHook`s included are all the ones that are needed for the metrics being tracked, but more can be easily added as necessary. Meanwhile, `isMetricsEnabled` is set to true only if the `CollectorHookFactory` field was non-nil. If it was `nil`, then none of the hooks can be created, and `isMetricsEnabled` is set to false so that any hook updates are ignored. This should only occur during `mongonet`-only tests.

Each type implementing a `MetricHook` implements `StartTimer()`, `StopTimer()`, `SetGauge()`, `AddCounterGauge()`, `IncCounterGauge()`, `DecGauge()`, and `SubGauge()`. The type must wrap a Prometheus metric, and by implementing these methods, it will be able to perform any basic action on its underlying metric. Any metric hook can be accessed from a `ProxySession` via the hooks map, provided that the programmer uses the same string key to access the metric as they did to insert it into the map in `CreateWorker()`. Lastly, each hook is utilized wherever necessary, using the appropriate method to modify the underlying metric provided that the hook was initialized in the first place (hence all of the `isMetricsEnabled` checks).

EVG: https://spruce.mongodb.com/version/5fb429d332f41719bd139d13/tasks

2020-11-18 09:32 UTC, TomerYakir requested changes

2020-11-18 09:32 UTC, TomerYakir commented on proxy.go
> +		err := requestDurationHook.StartTimer()
Let's start the timer after the message is successfully read so we don't count idle client time.
I think we're fine not timing failed attempts to read client messages.

2020-11-18 09:32 UTC, TomerYakir commented on proxy.go
> +			ps.logTrace(ps.proxy.logger, ps.proxy.config.TraceConnPool, "failed to start request duration metric hook timer %v", err)
`logTrace` logs at debug-level and is expected to be turned off by default. Let's change to `ps.proxy.logger.Logf(slogger.WARN, ....)`

2020-11-18 09:32 UTC, TomerYakir commented on proxy.go
> +		requestDurationHook.StopTimer()
[q] how do we distinguish between request_proxy_only and request_total?

2020-11-18 09:32 UTC, TomerYakir commented on proxy.go
> +				ps.logTrace(ps.proxy.logger, ps.proxy.config.TraceConnPool, "failed to start response duration metric hook timer %v", err)
same comment about logging

2020-11-18 09:32 UTC, TomerYakir commented on proxy.go
> +			responseDurationHook.StopTimer()
where do we distinguish between response_total and response_proxy_only?

2020-11-18 09:36 UTC, TomerYakir commented
Small comments from me.
One thing to note is that `mongonet` is actually agnostic to the way metrics are actually implemented, so I'd rephrase `The type must wrap a Prometheus metric` to `The type could (for example) wrap a Prometheus metric`.

2020-11-18 18:37 UTC, TomerYakir commented on proxy.go
> +		requestDurationHook.StopTimer()
[q] what would happen if we error on line 449 when starting the timer? could that potentially panic?

2020-11-18 19:32 UTC, varunravi98 commented on proxy.go
> +		requestDurationHook.StopTimer()
You're right, that could result in a panic. I could simply set a flag that indicates whether or not `requestDurationHook`'s timer was actually started and check that to stop the timer. The same solution could analogously be applied to `responseDurationHook`'s timer.
Alternatively, I could modify the implementation of `StopTimer()` to return an error if the underlying timer is `nil` (it shouldn't be if `StartTimer()` executed without error, and it will be if an error is returned or if `StartTimer()` wasn't called at all previously). That way, we don't have to add any checks here, but we would enforce that all types implementing `StopTimer()` must check that the underlying timer is non-nil and return an error if it is (or if anything else goes wrong when stopping the timer).

2020-11-18 20:25 UTC, varunravi98 commented on proxy.go
> +		requestDurationHook.StopTimer()
Per offline discussion, the first option was selected. The two flags are `isRequestTimerStarted` and `isResponseTimerStarted`, respectively.

2020-11-19 08:13 UTC, TomerYakir approved these changes
LGTM! 👍

2020-11-19 15:22 UTC, merged