Cursor server association support
mongodb/mongonet pull request #69
Opened 2021-01-27 23:03 UTC by tolsen

This adds support to mongonet for helping clients to associate a cursor with a particular server.

Louisa, I am assigning to you for now because Tomer is out until Sunday.  If we don't need this merged until next week then we can add Tomer as a reviewer.

2021-01-29 12:14 UTC, TomerYakir commented on wire.go
> +	panic(fmt.Errorf("unreachable"))
could we rephrase as something like `no body section found for OP_MSG`?

2021-01-29 12:15 UTC, TomerYakir commented on session.go
> +		return errors.New("Internal error")
[q] do we want to be more specific about the error here?

2021-01-29 12:18 UTC, TomerYakir requested changes
Added a few minor comments.
Do you suppose we can add an integration test to test out pinned server selection on mongonet?

2021-01-29 15:18 UTC, tolsen commented on wire.go
> +	panic(fmt.Errorf("unreachable"))
I believe we would have errored when we constructed the MessageMessage in the first place.  That's why I treated this more like an internal contract violation.  I'll see how onerous it is to thread an error response all the way up

2021-01-29 15:18 UTC, tolsen commented on wire.go
> +	panic(fmt.Errorf("unreachable"))
it's not that bad. i'll return an error

2021-01-29 15:26 UTC, tolsen commented on session.go
> +		return errors.New("Internal error")
fixed!

2021-01-29 15:26 UTC, tolsen commented
@TomerYakir comments addressed!

2021-01-29 16:18 UTC, tolsen commented
> Added a few minor comments.
> Do you suppose we can add an integration test to test out pinned server selection on mongonet?

just saw this question now.  i'll look to see what can be easily added

2021-02-08 10:40 UTC, TomerYakir commented
@louisaberger I added an int test for this and confirmed it's failing when the cursor isn't associated with the server address.
ready for review!

2021-02-08 14:12 UTC, louisaberger commented on inttests/int_test_utils.go
> +	fmt.Println("inserted", numOfDocs, "dummy docs")
Do we still need this statement?

2021-02-08 14:12 UTC, louisaberger commented on session.go
> +// do not call with OP_GET_MORE
Could you add a comment about _why_ we shouldn't call with OP_GET_MORE?

2021-02-08 14:12 UTC, louisaberger commented on wire.go
> +}
Why do we now calculate this each time in the new function instead?

2021-02-09 11:05 UTC, TomerYakir commented on inttests/int_test_utils.go
> +	fmt.Println("inserted", numOfDocs, "dummy docs")
removed!

2021-02-11 15:41 UTC, tolsen commented on session.go
> +// do not call with OP_GET_MORE
that function doesn't support OP_GET_MORE

2021-02-11 15:44 UTC, tolsen commented on wire.go
> +}
it's a derived field.  I don't see how the below function CommandDoc() is even remotely expensive to call.

The idea is less state, fewer bugs.  This way I got to remove a bunch of code that was intended to keep this field up to date.  I found myself having to add more of that code.  It just seems really error prone.

2021-02-11 16:27 UTC, louisaberger approved these changes

2021-02-12 06:56 UTC, merged